### ISSUE TITLE
Weber County 2012 numbers look weird

### ISSUE THREAD

**Issue by migurski** [openelections/openelections-sources-ut#5]
I’m trying to import Weber County 2012 for https://github.com/openelections/openelections-data-ut/issues/29 and finding some strange numbers. Here’s an example:

<img width="825" alt="Screen Shot 2020-02-01 at 10 41 21 AM" src="https://user-images.githubusercontent.com/58730/73597316-746e4180-44df-11ea-9371-bce4ca56ea6d.png">

The vote totals don’t add up: I see 116 registered voters in CYN001, but 168 votes for Attorney General in this excerpt. Should we look only at the last row of each five-row set? Do we have a less-ambiguous upstream copy of this data?

**Comment by dwillis** [comment]
@migurski They do look weird, although the five-row set represents four different modes of voting, with the fifth row being the total. I will see about trying to find a less ambiguous version of the data, but in the meantime if you wanted to grab the last of each five-row set and label that as `votes` that would suffice.

Update: [here](http://www.weberelections.com/documents/results/2012%20General%20Election%20-%20Statement%20of%20Votes%20Cast.pdf) is another version.

**Comment by migurski** [comment]
The fifth row of each set being the total makes more sense, now it looks like the other SOVC results.
